django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from .views import (
    HomePageView,
    ToDoListView,
    ToDoDetailView,
    ToDoCreateView,
    ToDoUpdateView,
    TodoDeleteView,
    todo_complete,
    todo_reactivate,
    ToDoListDetailView,
    ToDoListCreateView,
    ToDoListUpdateView,
    TodoListDeleteView,
    export_data,
    PrivacyPolicyView,
)

urlpatterns = [
    path("todos/", ToDoListView.as_view(), name="todo_list"),
    path("todos/export/", export_data, name="export_data"),
    path("todos/<int:pk>/", ToDoDetailView.as_view(), name="todo_detail"),
    path(
        "todos/new/<int:todo_list_pk>/",
        ToDoCreateView.as_view(),
        name="todo_new",
    ),
    path("todos/<int:pk>/edit/", ToDoUpdateView.as_view(), name="todo_edit"),
    path("todos/<int:pk>/delete/", TodoDeleteView.as_view(),
         name="todo_delete"),
    path("todos/<int:pk>/complete/", todo_complete, name="todo_complete"),
    path("todos/<int:pk>/reactivate/", todo_reactivate, name="todo_reactivate"),
    path("todos/lists/new/", ToDoListCreateView.as_view(),
         name="todo_list_new"),
    path(
        "todos/lists/<int:pk>/", ToDoListDetailView.as_view(),
        name="todo_list_detail"
    ),
    path(
        "todos/lists/<int:pk>/edit/",
        ToDoListUpdateView.as_view(),
        name="todo_list_edit",
    ),
    path(
        "todos/lists/<int:pk>/delete/",
        TodoListDeleteView.as_view(),
        name="todo_list_delete",
    ),
    path("legal/privacy-policy/", PrivacyPolicyView.as_view(),
         name="privacy-policy"),
    path("", HomePageView.as_view(), name="home"),
]

todos/models.py
from django.db import models
from django.urls import reverse


class ToDoList(models.Model):
    title = models.CharField(max_length=200, unique=True)
    creator = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("todo_list_detail", args=[str(self.pk)])


class ToDo(models.Model):
    title = models.CharField(max_length=200)
    details = models.TextField(blank=True, null=True)
    important = models.BooleanField(default=False)
    urgent = models.BooleanField(default=False)
    due_date = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    creator = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    todo_list = models.ForeignKey(
        "ToDoList",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("todo_detail", args=[str(self.pk)])

todos/forms.py
from django import forms
from django.forms import ModelForm

from .models import ToDo, ToDoList


class DateInput(forms.DateInput):
    input_type = "date"


class ToDoCreateForm(ModelForm):
    class Meta:
        model = ToDo
        fields = [
            "title",
            "details",
            "important",
            "urgent",
            "due_date",
        ]
        widgets = {
            "due_date": DateInput(),
        }


class ToDoUpdateForm(ModelForm):
    class Meta:
        model = ToDo
        fields = [
            "title",
            "details",
            "important",
            "urgent",
            "completed",
            "due_date",
            "todo_list",
        ]
        widgets = {
            "due_date": DateInput(),
        }


class ToDoListCreateForm(ModelForm):
    class Meta:
        model = ToDoList
        fields = ["title"]


class ToDoListUpdateForm(ModelForm):
    class Meta:
        model = ToDoList
        fields = ["title"]

todos/views.py
import csv

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import (
    ToDoCreateForm,
    ToDoUpdateForm,
    ToDoListCreateForm,
    ToDoListUpdateForm,
)
from .models import ToDo, ToDoList


class HomePageView(TemplateView):
    template_name = "home.html"


class ToDoListView(LoginRequiredMixin, ListView):
    model = ToDoList
    template_name = "todos/list_manager.html"

    def get_queryset(self):
        return ToDoList.objects.filter(creator=self.request.user.pk)


class ToDoDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = ToDo
    template_name = "todos/todo_detail.html"

    def test_func(self):
        obj = self.get_object()
        return obj.creator == self.request.user


class ToDoCreateView(LoginRequiredMixin, CreateView):
    model = ToDo
    form_class = ToDoCreateForm
    template_name = "todos/todo_new.html"
    context_object_name = "todo_list"
    pk_url_kwarg = "todo_list_pk"

    def get_success_url(self):
        todo_list_pk = self.object.todo_list_id
        return reverse("todo_list_detail", kwargs={"pk": todo_list_pk})

    def get_redirect_url(self, param):
        return reverse_lazy("todo_list_detail", kwargs={"param": param})

    def get_queryset(self):
        return ToDoList.objects.filter(pk=self.kwargs["todo_list_pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = ToDoCreateForm()
        context["todo_list"] = ToDoList.objects.get(pk=self.kwargs["todo_list_pk"])
        return context

    def form_valid(self, form):
        form.instance.todo_list = ToDoList.objects.get(pk=self.kwargs["todo_list_pk"])
        form.instance.creator = self.request.user
        return super().form_valid(form)


class ToDoUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = ToDo
    form_class = ToDoUpdateForm
    template_name = "todos/todo_edit.html"

    def get_success_url(self):
        todo_list_pk = self.object.todo_list_id
        return reverse("todo_list_detail", kwargs={"pk": todo_list_pk})

    def test_func(self):
        obj = self.get_object()
        return obj.creator == self.request.user


class TodoDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = ToDo
    template_name = "todos/todo_delete.html"

    def get_success_url(self):
        todo_list_id = self.object.todo_list.id
        return reverse_lazy("todo_list_detail", kwargs={"pk": todo_list_id})

    def test_func(self):
        obj = self.get_object()
        return obj.creator == self.request.user


def todo_complete(request, pk):
    if "_auth_user_id" not in request.session:
        return redirect("/")
    model = ToDo.objects.get(pk=pk)
    if request.session["_auth_user_id"] != str(model.creator.pk):
        return redirect("home")
    else:
        model.completed = True
        model.save()
        return redirect("todo_list_detail", pk=model.todo_list.pk)


def todo_reactivate(request, pk):
    if "_auth_user_id" not in request.session:
        return redirect("/")
    model = ToDo.objects.get(pk=pk)
    if request.session["_auth_user_id"] != str(model.creator.pk):
        return redirect("home")
    else:
        model.completed = False
        model.save()
        return redirect("todo_list_detail", pk=model.todo_list.pk)


class ToDoListDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = ToDoList
    template_name = "todos/todo_list_detail.html"
    context_object_name = "todo_list"
    pk_url_kwarg = "pk"

    def test_func(self):
        todo_list = self.get_object()
        return todo_list.creator == self.request.user

    def get_queryset(self):
        return ToDoList.objects.filter(pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        todo_list = self.get_object()
        context["do_list"] = ToDo.objects.filter(todo_list=todo_list, completed=False, important=True, urgent=True)

        context["schedule_list"] = ToDo.objects.filter(todo_list=todo_list,
                                                 completed=False,
                                                 important=True, urgent=False)
        context["delegate_list"] = ToDo.objects.filter(todo_list=todo_list,
                                                 completed=False,
                                                 important=False, urgent=True)
        context["eliminate_list"] = ToDo.objects.filter(todo_list=todo_list,
                                                 completed=False,
                                                 important=False, urgent=False)
        context["completed_list"] = ToDo.objects.filter(todo_list=todo_list, completed=True)
        context["list_name"] = todo_list.title
        context["list_pk"] = todo_list.pk
        return context


class ToDoListCreateView(LoginRequiredMixin, CreateView):
    model = ToDoList
    form_class = ToDoListCreateForm
    template_name = "todos/todo_list_new.html"

    def get_success_url(self):
        todo_list_pk = self.object.id
        return reverse("todo_list_detail", kwargs={"pk": todo_list_pk})

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class ToDoListUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = ToDoList
    form_class = ToDoListUpdateForm
    template_name = "todo_list_edit.html"
    success_url = reverse_lazy("todo_list")

    def test_func(self):
        obj = self.get_object()
        return obj.creator == self.request.user


class TodoListDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = ToDoList
    template_name = "todos/todo_list_delete.html"
    success_url = reverse_lazy("todo_list")

    def test_func(self):
        obj = self.get_object()
        return obj.creator == self.request.user


def export_data(request):
    query_set = ToDo.objects.filter(creator=request.user.pk).order_by(
        "todo_list__title"
    )
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="exported_data.csv"'},
    )
    writer = csv.writer(response)

    writer.writerow(
        [
            "Title",
            "Details",
            "Important",
            "Urgent",
            "Due Date",
            "Completed",
            "ToDo List",
        ]
    )
    for item in query_set:
        writer.writerow(
            [
                item.title,
                item.details,
                item.important,
                item.urgent,
                item.due_date,
                item.completed,
                item.todo_list,
            ]
        )

    return response


class PrivacyPolicyView(TemplateView):
    template_name = "privacy_policy.html"

templates/todos/detail_partial.html
{% block detail_partial %}

<div class="d-flex justify-content-between border-bottom align-items-start">
    <div>
        <p class="fw-bold">{{todo.title}}</p>
    </div>
    <div class="d-flex">
        <!-- Detail Modal -->
        <div class="modal fade" id="detail{{todo.pk}}"
             tabindex="-1"
             aria-labelledby="{{todo.pk}}Label"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header card-header">
                        <h2 class="modal-title fs-5"
                            id="{{todo.pk}}Label">
                            {{ todo.title }}</h2>
                        <button type="button"
                                class="btn-close"
                                data-bs-dismiss="modal"
                                aria-label="Close"></button>
                    </div>
                    <div class="modal-body card-body">
                        <p class="card-text">Task Details:
                            {{ todo.details }}</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Due
                                Date: {{ todo.due_date }}
                            </li>

                            {% if todo.important %}
                            <li class="list-group-item fw-bold">
                                Important
                            </li>
                            {% endif %}

                            {% if todo.urgent %}
                            <li class="list-group-item fw-bold">
                                Urgent
                            </li>
                            {% endif %}

                            {% if todo.completed %}
                            <li class="list-group-item">
                                Completed
                            </li>
                            {% else %}
                            <li class="list-group-item fw-bold">
                                Incomplete
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="modal-footer card-footer">
                        {% if todo.completed %}
                        <a class="btn btn-success"
                           href="{% url 'todo_reactivate' todo.pk %}">
                            Reactivate
                        </a>
                        {% else %}
                        <a class="btn btn-success"
                           href="{% url 'todo_complete' todo.pk %}">
                            Complete
                        </a>
                        {% endif %}
                        <a class="btn btn-secondary"
                           href="{% url 'todo_edit' todo.pk %}">
                            Edit
                        </a>
                        <a class="btn btn-outline-secondary"
                           href="{% url 'todo_delete' todo.pk %}">
                            Delete
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!--End Detail Modal-->

        <a href="#detail{{todo.pk}}"
           class="ms-2 text-secondary"
           data-bs-toggle="modal"
           data-bs-target="#detail{{todo.pk}}">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24" fill="currentColor"
                 class="bi bi-info-square"
                 viewBox="0 0 16 16">
                <title>View details for {{todo.title}}</title>
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
            </svg>
        </a>
        <a href="{% url 'todo_edit' todo.pk %}"
           class="ms-2 text-secondary">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24" fill="currentColor"
                 class="bi bi-pencil-square"
                 viewBox="0 0 16 16">
                <title>Edit {{todo.title}}</title>
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd"
                      d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
            </svg>
        </a>
        <a href="{% url 'todo_delete' todo.pk %}"
           class="ms-2 text-danger">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24" fill="currentColor"
                 class="bi bi-x-square" viewBox="0 0 16 16">
                <title>Delete {{todo.title}}</title>
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
            </svg>
        </a>
        <a href="{% url 'todo_complete' todo.pk %}"
           class="ms-2 text-success">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="24"
                 height="24" fill="currentColor"
                 class="bi bi-check-square"
                 viewBox="0 0 16 16">
                <title>Complete {{todo.title}}</title>
                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425z"/>
            </svg>
        </a>
    </div>
</div>

{% endblock detail_partial %}

templates/todos/list_manager.html
{% extends "base.html" %}

{% block title %}ToDo List Manager{% endblock title%}

{% block content %}

<h1>List Manager</h1>
<table class="table table-sm mt-4">
    <thead>
    <tr>
        <th scope="col">List Name</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody class="table-group-divider">
    {% for todo_list in todolist_list %}
    <tr>
        <td class="py-3">
            <a href="{{ todo_list.get_absolute_url }}"
               class="link-success fw-bold">
                {{ todo_list.title }}</a>
        </td>
        <td class="py-3">
            <div class="d-flex">
                <a href="{{ todo_list.get_absolute_url }}"
                   class="ms-2 text-secondary">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         width="24"
                         height="24" fill="currentColor"
                         class="bi bi-info-square"
                         viewBox="0 0 16 16">
                        <title>View details for {{todo_list.title}}</title>
                        <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                        <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
                    </svg>
                </a>
                <a href="{{ todo_list.get_absolute_url }}"
                   class="ms-2 text-secondary">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         width="24"
                         height="24" fill="currentColor"
                         class="bi bi-pencil-square"
                         viewBox="0 0 16 16">
                        <title>Edit {{todo_list.title}}</title>
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd"
                              d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                    </svg>
                </a>
                <a href="{{ todo_list.get_absolute_url }}"
                   class="ms-2 text-danger">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         width="24"
                         height="24" fill="currentColor"
                         class="bi bi-x-square" viewBox="0 0 16 16">
                        <title>Delete {{todo_list.title}}</title>
                        <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
                    </svg>
                </a>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock content %}

templates/todos/todo_delete.html
{% extends "base.html" %}

{% block title %}Delete ToDo Item{% endblock title %}

{% block content %}
<div class="col-lg-6 col-10 card bg-body-tertiary mx-auto">
    <div class="card-header">
        <h1>Delete {{ object.title }}</h1>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete this task?</p>
            <button type="submit" class="btn btn-danger">Confirm</button>
            <a class="btn btn-secondary"
               href="{% url 'todo_list_detail' todo.todo_list.pk %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock content %}

templates/todos/todo_detail.html
{% extends "base.html" %}

{% block title %}ToDo Detail{% endblock title %}

{% block content %}
<div class="card bg-body-tertiary">
    <div class="card-header">
        <h1>{{ todo.title }}</h1>
    </div>
    <div class="card-body">
        <div class="card-body">
            <p class="card-text">Task Details: {{ todo.details }}</p>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Due Date: {{ todo.due_date }}</li>

                {% if todo.important %}
                <li class="list-group-item fw-bold">Important</li>
                {% endif %}

                {% if todo.urgent %}
                <li class="list-group-item fw-bold">Urgent</li>
                {% endif %}

                {% if todo.completed %}
                <li class="list-group-item">Completed</li>
                {% else %}
                <li class="list-group-item fw-bold">Incomplete</li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="card-footer">
        {% if todo.completed %}
        <a class="btn btn-success"
           href="{% url 'todo_reactivate' todo.pk %}">Reactivate task
        </a>
        {% else %}
        <a class="btn btn-success"
           href="{% url 'todo_complete' todo.pk %}">Complete task
        </a>
        {% endif %}
        <a class="btn btn-secondary" href="{% url 'todo_edit' todo.pk %}">
            Edit ToDo
        </a>
        <a class="btn btn-outline-secondary"
           href="{% url 'todo_delete' todo.pk %}">
            Delete ToDo
        </a>
        <a class="btn btn-link"
           href="{% url 'todo_list_detail' todo.todo_list.pk %}">
            Back to ToDo List
        </a>
    </div>
</div>
{% endblock content %}

templates/todos/todo_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit ToDo Item{% endblock title %}

{% block content %}
<div class="col-lg-6 col-10 card bg-body-tertiary mx-auto">
    <div class="card-header">
        <h1>Edit {{ object.title }}</h1>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Update</button>
            <a class="btn btn-secondary"
               href="{% url 'todo_list_detail' todo.todo_list.pk %}">
                Cancel
            </a>
        </form>
    </div>
</div>
{% endblock content %}

templates/todos/todo_list_delete.html
{% extends "base.html" %}

{% block title %}Delete ToDo List{% endblock title %}

{% block content %}
<div class="col-lg-6 col-10 card bg-body-tertiary mx-auto">
    <div class="card-header">
        <h1>Delete "{{ object.title }}"</h1>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete this list?</p>
            <button type="submit" class="btn btn-danger">Delete</button>
            <a class="btn btn-secondary"
               href="{% url 'todo_list' %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock content %}

templates/todos/todo_list_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit ToDo List{% endblock title %}

{% block content %}
<div class="card bg-body-tertiary">
    <div class="card-header">
        <h1>Edit "{{ object.title }}"</h1>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Update</button>
            <a class="btn btn-secondary"
               href="{% url 'todo_list' %}">Cancel
            </a>
        </form>
    </div>
</div>
{% endblock content %}

templates/todos/todo_list_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}New ToDo List{% endblock title %}

{% block content %}
<div class="col-lg-6 col-10 card bg-body-tertiary mx-auto">
    <div class="card-header">
        <h1>Start a New List</h1>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Save</button>
        </form>
    </div>
</div>
{% endblock content %}

templates/todos/todo_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}New ToDo Item{% endblock title %}

{% block content %}
<div class="col-lg-6 col-10 card bg-body-tertiary mx-auto">
    <div class="card-header">
        <h1>New Task</h1>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Save</button>
        </form>
    </div>
</div>
{% endblock content %}